name: FEMINA Movement
favicon: null
layout_spectrum: 0.847104209009558
typography_spectrum: 0.9110288147348911
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.41430111904628575
  lightness: 0.6004397734068334
  saturation: 0.834120772080496
  rhythmicContrast: 0.7944814525544643
purpose: []
