name: FEMINA Movement
favicon: null
layout_spectrum: 0.99729
typography_spectrum: 0.75
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5f5f5'
    - '#c7c7c7'
    - '#36312c'
    - '#5d605c'
    - '#f56b6e'
  brandStrength: 0.41430111904628575
  lightness: 0.6004397734068334
  saturation: 0.834120772080496
  rhythmicContrast: 0.7944814525544643
purpose: []
