name: FEMINA Movement
favicon: null
layout_spectrum: 0.99729
typography_spectrum: 0.75
title: FEMINA MovementFeel. Empower.Nourish.Inspire.Align
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#971f21'
    - '#58184a'
    - '#f7a051'
    - '#fdc973'
    - '#fff0b5'
  brandStrength: 0.41430111904628575
  lightness: 0.6004397734068334
  saturation: 0.834120772080496
  rhythmicContrast: 0.7944814525544643
purpose: []
